{"name": "test_add", "status": "failed", "statusDetails": {"message": "AssertionError: assert 15 == 16\n +  where 15 = <function Calc.add at 0x0000029E1E61AE50>(1, 2, 12)\n +    where <function Calc.add at 0x0000029E1E61AE50> = <src.a_pytest.b_sequence.Calc.Calc object at 0x0000029E1E8B9A30>.add\n +      where <src.a_pytest.b_sequence.Calc.Calc object at 0x0000029E1E8B9A30> = <src.a_pytest.b_sequence.test_case.TestClass object at 0x0000029E1E8A9D30>.c", "trace": "self = <src.a_pytest.b_sequence.test_case.TestClass object at 0x0000029E1E8A9D30>\n\n    def test_add(self):\n>       assert self.c.add(1, 2, 12) == 16\nE       assert 15 == 16\nE        +  where 15 = <function Calc.add at 0x0000029E1E61AE50>(1, 2, 12)\nE        +    where <function Calc.add at 0x0000029E1E61AE50> = <src.a_pytest.b_sequence.Calc.Calc object at 0x0000029E1E8B9A30>.add\nE        +      where <src.a_pytest.b_sequence.Calc.Calc object at 0x0000029E1E8B9A30> = <src.a_pytest.b_sequence.test_case.TestClass object at 0x0000029E1E8A9D30>.c\n\nsrc\\a_pytest\\b_sequence\\test_case.py:19: AssertionError"}, "attachments": [{"name": "stdout", "source": "45ac9bc9-2e39-4e5d-828e-cd99121d4dbd-attachment.txt", "type": "text/plain"}], "start": 1578630425891, "stop": 1578630425891, "uuid": "9f02cd96-839e-4baa-958d-9ec4fb0c8261", "historyId": "74f59845f0ee31bcdde039c10c0f1bdc", "testCaseId": "6d6ec2d922a6c434a19194f5b6d58a29", "fullName": "src.a_pytest.b_sequence.test_case.TestClass#test_add", "labels": [{"name": "parentSuite", "value": "src.a_pytest.b_sequence"}, {"name": "suite", "value": "test_case"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "GELOMEN-PC"}, {"name": "thread", "value": "9476-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.a_pytest.b_sequence.test_case"}]}